pipeline:

  build_stage:
    image: plugins/docker
    repo: iggalleguillo/testdroneagibiz
    dockerfile: Dockerfile 
    secrets: [ docker_username, docker_password ]
    tags:
      - v-${DRONE_BUILD_NUMBER}
    
  deploy_stage:
    image: codestation/drone-stack
    host: tcp://192.168.99.104:2376 
    stack_name: testdockerswarm
    compose: stack.yml
    registry: hub.docker.com/iggalleguillo/testdroneagibiz
    secrets: [ docker_username, docker_password ]
    meta_data:
      REPLICAS: 1