pipeline:

  build_stage:
    image: plugin/docker
    registry: docker.io
    repo: iggalleguillo/testdockerswarm
    dockerfile: Dockerfile
    tags: latest 
    secrets: [ docker_username, docker_password ] 
    