pipeline:

  build_stage:
    image: plugins/docker
    repo: iggalleguillo/testdroneagibiz
    dockerfile: Dockerfile 
    secrets: [ docker_username, docker_password ]
    tags:
      - v-${DRONE_BUILD_NUMBER}
    
  code-analysis_stage:
    image: aosapps/drone-sonar-plugin
    settings:
        sonar_host: http://192.168.99.100:4300
        sonar_token: 083310af56a37ac38e589e8454ca3f7f15062fe0
    ver: v-${DRONE_BUILD_NUMBER}
    sources: .
    level: DEBUG
    showProfiling: true

  deploy_stage:
    image: codestation/drone-stack
    host: tcp://192.168.99.104:2376 
    stack_name: testdockerswarm
    compose: stack.yml
    registry: https://index.docker.io/v1/
    secrets: [ docker_username, docker_password ]
    meta_data:
      REPLICAS: 1