pipeline:

  build_stage:
    image: plugins/docker
    repo: iggalleguillo/testdroneagibiz
    dockerfile: Dockerfile 
    secrets: [ docker_username, docker_password ]
    tags:
      - v-${DRONE_BUILD_NUMBER}
    
  code-analysis_stage:
    image: aosapps/drone-sonar-plugin
    settings:
        sonar_host: http://punto.agibiz.cl:4203
        sonar_token: b7b54630c0e3a57716677acc7a1576ff601df759
    ver: v-${DRONE_BUILD_NUMBER}
    sources: .
    level: DEBUG
    showProfiling: true

  deploy_stage:
    image: codestation/drone-stack
    host: tcp://192.168.99.104:2376 
    stack_name: testdockerswarm
    compose: stack.yml
    registry: https://index.docker.io/v1/
    secrets: [ docker_username, docker_password ]
    meta_data:
      REPLICAS: 1