pipeline:

  build_stage:
    image: plugins/docker
    repo: iggalleguillo/testdroneagibiz
    dockerfile: Dockerfile
    tags: latest 
    secrets: [ docker_username, docker_password ] 
    
    
  deploy_stage:
    image: codestation/drone-stack
    host: tcp://192.168.0.103:2376
    stack_name: testdockerswarm
    