version: '3.2'

services:
  api:
    image: https://cloud.docker.com/u/iggalleguillo/repository/docker/iggalleguillo/testdroneagibiz:48
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 512M
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 5
        window: 30s
    ports:
      - "80:80"
